### ISSUE TITLE
GUI application stutters when monkey patching the `time` module

### ISSUE THREAD

**Issue by danielhrisca** [zariiii9003/win-precise-time#3]
Hello,

I'm monkey patching the standard library `time` module like this

```python
from win_precise_time import sleep as wpsleep
from win_precise_time import time as wptime
import time
time.sleep = wpsleep
time.time = wptime
```

If I do this I see that the GUI application stutters. The smallest sleep used in the application is 1ms 
```python
sleep(0.001)
```

Any idea what might be wrong?

```
CPython 3.10 x64
Windows 11 x64
win_precise_time == 1.4.0
```

**Comment by zariiii9003** [comment]
Do you have a branch, where i can see your use case?

Generally i would say, don't use sleep in your Qt event loop, because it blocks execution. Use [QTimer](https://doc.qt.io/qt-5/qtimer.html#singleShot-1) instead.

```python3
    def loop_func(self) -> None:
        # your code
        if not self._stopped:
            QTimer.singleShot(20, self.loop_func)
```

There's also a [PreciseTimer](https://doc.qt.io/qt-5/qt.html#TimerType-enum) option, but i don't know how well that works.

**Comment by zariiii9003** [comment]
I just tried doing the same in my app, and indeed weird things happen, when i replace `time.sleep`. I'll look into it.

**Comment by zariiii9003** [comment]
It's hopefully fixed in https://github.com/zariiii9003/win-precise-time/commit/4ffb988410a3b6dacf9855b7558a84617f2dd33e and v1.4.1.

**Comment by danielhrisca** [comment]
The fix is working correctly! Thanks!
